### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by pbassham** [Weetbix/facebot#23]
I tried running it on Heroku, but it crashes. Here is the log

```
2017-11-23T01:43:01.398687+00:00 heroku[worker.1]: State changed from starting to up
2017-11-23T01:43:04.397275+00:00 app[worker.1]: 
2017-11-23T01:43:04.397291+00:00 app[worker.1]: > facebot@0.0.8 start /app
2017-11-23T01:43:04.397292+00:00 app[worker.1]: > node bin/run_postgres.js
2017-11-23T01:43:04.397292+00:00 app[worker.1]: 
2017-11-23T01:43:06.373593+00:00 app[worker.1]: module.js:340
2017-11-23T01:43:06.373606+00:00 app[worker.1]:     throw err;
2017-11-23T01:43:06.373607+00:00 app[worker.1]:     ^
2017-11-23T01:43:06.373607+00:00 app[worker.1]: 
2017-11-23T01:43:06.373609+00:00 app[worker.1]: Error: Cannot find module 'js-emoji'
2017-11-23T01:43:06.373610+00:00 app[worker.1]:     at Function.Module._resolveFilename (module.js:338:15)
2017-11-23T01:43:06.373610+00:00 app[worker.1]:     at Function.Module._load (module.js:289:25)
2017-11-23T01:43:06.373611+00:00 app[worker.1]:     at Module.require (module.js:366:17)
2017-11-23T01:43:06.373611+00:00 app[worker.1]:     at require (module.js:385:17)
2017-11-23T01:43:06.373612+00:00 app[worker.1]:     at Object.<anonymous> (/app/lib/facebot.js:9:13)
2017-11-23T01:43:06.373613+00:00 app[worker.1]:     at Module._compile (module.js:435:26)
2017-11-23T01:43:06.373613+00:00 app[worker.1]:     at Object.Module._extensions..js (module.js:442:10)
2017-11-23T01:43:06.373613+00:00 app[worker.1]:     at Module.load (module.js:356:32)
2017-11-23T01:43:06.373614+00:00 app[worker.1]:     at Function.Module._load (module.js:313:12)
2017-11-23T01:43:06.373615+00:00 app[worker.1]:     at Module.require (module.js:366:17)
2017-11-23T01:43:06.373615+00:00 app[worker.1]:     at require (module.js:385:17)
2017-11-23T01:43:06.373616+00:00 app[worker.1]:     at Object.<anonymous> (/app/bin/run_postgres.js:7:15)
2017-11-23T01:43:06.373616+00:00 app[worker.1]:     at Module._compile (module.js:435:26)
2017-11-23T01:43:06.373617+00:00 app[worker.1]:     at Object.Module._extensions..js (module.js:442:10)
2017-11-23T01:43:06.373618+00:00 app[worker.1]:     at Module.load (module.js:356:32)
2017-11-23T01:43:06.373618+00:00 app[worker.1]:     at Function.Module._load (module.js:313:12)
2017-11-23T01:43:06.390303+00:00 app[worker.1]: 
2017-11-23T01:43:06.397610+00:00 app[worker.1]: npm ERR! Linux 3.13.0-133-generic
2017-11-23T01:43:06.398232+00:00 app[worker.1]: npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
2017-11-23T01:43:06.398581+00:00 app[worker.1]: npm ERR! node v4.2.4
2017-11-23T01:43:06.399794+00:00 app[worker.1]: npm ERR! npm  v2.14.12
2017-11-23T01:43:06.400131+00:00 app[worker.1]: npm ERR! code ELIFECYCLE
2017-11-23T01:43:06.400424+00:00 app[worker.1]: npm ERR! facebot@0.0.8 start: `node bin/run_postgres.js`
2017-11-23T01:43:06.400659+00:00 app[worker.1]: npm ERR! Exit status 1
2017-11-23T01:43:06.400888+00:00 app[worker.1]: npm ERR! 
2017-11-23T01:43:06.401097+00:00 app[worker.1]: npm ERR! Failed at the facebot@0.0.8 start script 'node bin/run_postgres.js'.
2017-11-23T01:43:06.401347+00:00 app[worker.1]: npm ERR! This is most likely a problem with the facebot package,
2017-11-23T01:43:06.401611+00:00 app[worker.1]: npm ERR! not with npm itself.
2017-11-23T01:43:06.401823+00:00 app[worker.1]: npm ERR! Tell the author that this fails on your system:
2017-11-23T01:43:06.402062+00:00 app[worker.1]: npm ERR!     node bin/run_postgres.js
2017-11-23T01:43:06.402284+00:00 app[worker.1]: npm ERR! You can get their info via:
2017-11-23T01:43:06.402535+00:00 app[worker.1]: npm ERR!     npm owner ls facebot
2017-11-23T01:43:06.411135+00:00 app[worker.1]: npm ERR! There is likely additional logging output above.
2017-11-23T01:43:06.415226+00:00 app[worker.1]: 
2017-11-23T01:43:06.422813+00:00 app[worker.1]: npm ERR! Please include the following file with any support request:
2017-11-23T01:43:06.423088+00:00 app[worker.1]: npm ERR!     /app/npm-debug.log
2017-11-23T01:43:06.575433+00:00 heroku[worker.1]: State changed from up to crashed
2017-11-23T01:43:06.559740+00:00 heroku[worker.1]: Process exited with status 1
```

**Comment by tjsoftworks** [comment]
I confirm it does not work on the master branch either on Heroku or Local to my machine due to this js-emoji error. I cannot tell if this error has been handled via https://github.com/mitchcapper 's Pull Request nor can I seem to get his branch to work for other reasons....

**Comment by jonhcase** [comment]
I ran into the same issue. I noticed that this contains the dependency js-emoji (https://www.npmjs.com/package/js-emoji) rather than emoji-js (https://www.npmjs.com/package/emoji-js).

If I install the dependencies manually and substitute emoji-js in place of js-emoji it seems to run locally and connect to Facebook. Still haven't been able to successfully connect to a chat though.

**Comment by Weetbix** [comment]
Hi guys, 

I've updated master and I can run the bot both locally and remotely on heroku. 

Let me know if you have any more trouble 👍
